init:
- git config --global core.autocrlf true
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
build_script:
- ps: .\run.ps1 -ci default-build
clone_depth: 1
test: 'off'
deploy: 'off'
os: Visual Studio 2017
