language: csharp
sudo: required
dist: trusty
services:
  - docker
addons:
  apt:
    packages:
    - libunwind8
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - dev
    - feature/dev-si
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
script:
  - ./build.sh
#  Temporarily disabled systemd activation test: https://github.com/aspnet/KestrelHttpServer/issues/1912#issuecomment-311162419
#  - if test "$TRAVIS_OS_NAME" != "osx"; then bash test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/SystemdActivation/docker.sh; fi
