init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - feature/dev-si
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
build_script:
  - ps: .\build.ps1
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
