
var VERSION='0.1'
var FULL_VERSION='0.1'
var AUTHORS='Microsoft'

use-standard-lifecycle
k-standard-goals
custom-goals

#repo-initialize target='initialize'
    git gitCommand="submodule update --init"
    k-restore